### How to use this document
# 1. Fill in your info
# 2. Re-excecute the build in the command line with: bundle exec jekyll serve
# 3. Push to github
# NOTE: it looks like you need to rebuild + repush everytime you update this _config.yml file

### Site Settings ###
title               : YOON RESUME 
description         : >-
                      Nice to meet you! I'm Seoyoung
baseurl             : ""   # Change to empty quotes if you are hosting your site at <your-username>.github.io directly,
#                                             otherwise will be hosted at <your-username>.github.io/{{base_url}}
repository          : seoyoung-aspyn/seoyoung-aspyn.github.io                    # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects) -- for example, I would put "jnaiman" without the quotes after the ":" here
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2
  - mini_magick

### To specify which port to host locally on -- use if you have multiple sites you want to host 
port: 4008

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Seoyoung Yoon
  image             : 'https://lh3.googleusercontent.com/fife/AK0iWDwJS5zksqFc4rG_oG89PJB2zPj9syEXLMO8rb2j5q5qSgftW_FwBQzPfm_E_qBYVcwXN0HqBoztiwXZM2m_kSKEtUFVZjqRpDZjdnuJVJ22ncPwnbBwrkciZb2BF2oHqXrZKw0qnUxU5xr2qBw2dlioQFsuj9ABMfHfG3et0xgY3pC7HCDTbZ-PR3NLfLEFOen5mOff5Kxsq-4YMUb75YUnLy5KmtRK4ylY_xzH89u-U-36jvMctH39VVqDshA3kx_oQOUPd1NaonQ1lcU0lF2q-VyON46Q0-IpnA9vKEvYpVYTCmzlcWJshtZVWgi0q6wJbae6cJ1m4hDPOFcwXaDwacJw3KgIj1pLZQFBHVmNzxlzGC29vf_tmqHiFjt_LjezpPcIm958_eCDQwQx7OKGly3ihymqSSt-o2R7qWj_bUZWRTlbIfqRGZeSbESY4Qh8fH7SFFLsZ-KCpqeSlAe6lTWXBkW7bLDqXAGuHb14J3UvRf6hT_cBU66BxNo_o5W1Gfq5nIEInctfO1kcWqNKRcr-FSiGWtV9IwfNevNFmd8wB1lxVu-QRQww2JGd8TenB5Y-bq3WP0BHcf-qMDnKaOKlFtDlwyXeIKvIxDvbbp1D-jzKXzMBe7UliGUizMPUcqUaPF2nxIjmc6p60hMKbDsrc0SEO6IAHMhyRngoQJDJU_ww0mw3dhEma9Xh1yAwHUsetFPOI6Uir20ToCBez7_e-YddFjUiLtChlLl7LKLKPPLvb43Aws6IA76x32r4qMckUJhNszT8zvcNev-bRW4-95Nhe9ovAz7RLmDMbqwmHVQFN7_m1UZXSfdWy3Z_691j4y7abxwcX4FP9uuo-r-r2GM9omKNm8Os-801sZbozcqtBehs9EoupulWZZtH_AbfdsZdMlwx0yVynGruQjAOq9HYs2O9qeKjukZExRntkZG_DtM8mSMEDO-ko95Aov4qXa3ZSf2txJ39zC020Igd0Kd6k6vQFg8_yOxSTRiwb-Ofy427zEL0-di-0COSb-JwYv6-6coE707MIOLBikuI-ZWInhEhet65jzPsHYwN9kuCF5jhxQusmlpMFl6ETKGu7VilABaNvNfFUjtqY0-QA-84ZZuJz0x_JZ6sMY46xBtYL_4HxhOQr8BXJwE-HvHMT4sXXu0V4OdTZQQ_qRfXrLl0Yyq74KMAsMutpgKLwMPU55jAxqo79PYHiHkcQ6FMh8vE1hgF27SjA6bSAux-fmiFLMHjBNFh7qj49o2fMcVOv76WH2aYe0-efSXYJLVUo-3LanEAiEktJVAXC2eFDLROBSvAS_Jg2_U-KWfbopFdVv9d7NDOuH1VviaBupsDjWuxDZDopqk-99YX5VSRckS8XwqIJe_SiXl-w3ho7j7kA4A0cT3E5Enpzyw7BivRQCmzwsGLZM1VIUss2O_sDNoKenjAl-8Sg_un5gQvGbzcPKxTpHoSMAbbmJ9dF-APp_Ms9QJLj6KfEkCc4bDr6H9itcYmARPVlTJnLiMr8z6pyQZjTrsFXTJMzzzp8dpophoH81xvXYc3b9yhgteqRfLykBf8Wxhkfk2YdnJp1PwumX6Wg1ikfzRfkhe0E8uTTnxVYv7M30HHpdVzFcUo9Hq1vr6n79JKvwf5IfWFwQ3sDtk=w1684-h1218'
#  behance           : your_username
# dribbble          : your_username
  email             : sy63@illinois.edu
#  facebook          : your_username
  github            : seoyoung-aspyn # JPN
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : aspynyoon
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
#  twitch            : your_username
#  twitter           : your_username
#  vimeo             : your_username
#  youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: SY Yoon                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
## Add yours here if you have other stuff in your github.io page!!!**
exclude:
  - README.md
  - README.md~
  - CONTRIBUTING.md
  - LICENSE.md
  - LICENSE.md~
  - config.yml~
  - "*.log"
  - "*.ipynb"
  - "python_notebooks/*"
